#!/usr/bin/env python

from scapy.all import *
from scapy.error import Scapy_Exception

filter_message="tcp"
count=0

def pktTCP(pkt):
        global count
        if pkt.haslayer(TCP) and pkt.getlayer(TCP).dport == 80 and pkt.haslayer(Raw):
                count=count+1
                print pkt.getlayer(Raw).load

sniff(prn=pktTCP,filter="tcp")